#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: The Blacklist

# Short bio or description (displayed in the header)
description: Internet Nomad

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/Don-Gato-Coded/Don-Gato-Coded.Github.Io/refs/heads/master/images/gato1.jpeg 
# https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
#
# Flags below are optional
#


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: don.gato.coded@gmail.com
  facebook:
  flickr:
  github: Don-Gato-Coded
  instagram:
  linkedin:
  pinterest:
  rss: rss
  twitter: miblanco4
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://don-gato-coded.github.io/TheBlackList/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/TheBlackList"
imagesurl: https://don-gato-coded.github.io/TheBlackList/images

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME